-- Catalogue fourni : pf2e_huiles_elixirs_potions_AoN.csv (338 références).
-- Import uniquement : aucun inventaire de campagne n'est modifié.
-- Les liens sources sont des pages de catégorie AoN, pas des fiches individuelles.
-- Réexécutable sans doublon. Les prix absents restent NULL.
begin;

alter table public.pf2e_equipment_references
  add column if not exists item_type text,
  add column if not exists level integer check (level is null or level >= 0),
  add column if not exists rarity text;

-- Une page source peut désormais documenter plusieurs objets.
alter table public.pf2e_equipment_references
  drop constraint if exists pf2e_equipment_references_aon_url_key;
create unique index if not exists pf2e_equipment_references_source_name_key
  on public.pf2e_equipment_references (aon_url, name_en);

insert into public.pf2e_equipment_references
  (source_tab, equipment_kind, name_en, price_label, price_cp, aon_url, item_type, level, rarity)
values
  ('Potion', 'consumable', 'Gecko Potion', '3 gp', 300, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 1, 'Common'),
  ('Potion', 'consumable', 'Healing Potion (Minor)', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 1, 'Common'),
  ('Potion', 'consumable', 'Minor Soldier''s Syrup', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 1, 'Uncommon'),
  ('Potion', 'consumable', 'Potion of Emergency Escape', '3 gp', 300, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 1, 'Common'),
  ('Potion', 'consumable', 'Potion of Retaliation (Minor)', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 1, 'Common'),
  ('Potion', 'consumable', 'Potion of Shared Memories', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 1, 'Common'),
  ('Potion', 'consumable', 'Ration Tonic', '3 gp', 300, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 1, 'Common'),
  ('Potion', 'consumable', 'Antivenom Potion', '6 gp', 600, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 2, 'Common'),
  ('Potion', 'consumable', 'Draft of Stellar Radiance', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 3, 'Rare'),
  ('Potion', 'consumable', 'Lesser Soldier''s Syrup', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 3, 'Uncommon'),
  ('Potion', 'consumable', 'Potion of Retaliation (Lesser)', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 3, 'Common'),
  ('Potion', 'consumable', 'Potion of Water Breathing', '11 gp', 1100, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 3, 'Common'),
  ('Potion', 'consumable', 'Bloodhammer Reserve', '20 gp', 2000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 4, 'Uncommon'),
  ('Potion', 'consumable', 'Bottled Omen', '20 gp', 2000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 4, 'Rare'),
  ('Potion', 'consumable', 'Invisibility Potion', '20 gp', 2000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 4, 'Uncommon'),
  ('Potion', 'consumable', 'Oak Potion', '15 gp', 1500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 4, 'Common'),
  ('Potion', 'consumable', 'Potion of Passing Fancy', '20 gp', 2000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 4, 'Uncommon'),
  ('Potion', 'consumable', 'Shrinking Potion', '15 gp', 1500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 4, 'Common'),
  ('Potion', 'consumable', 'Sure-Step Potion', '17 gp', 1700, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 4, 'Common'),
  ('Potion', 'consumable', 'Fu Water', '21 gp', 2100, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 5, 'Common'),
  ('Potion', 'consumable', 'Green Wyrmling Breath Potion', '30 gp', 3000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 5, 'Common'),
  ('Potion', 'consumable', 'Potion of Disguise (Lesser)', '30 gp', 3000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 5, 'Uncommon'),
  ('Potion', 'consumable', 'Potion of Resistance (Lesser)', '45 gp', 4500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 5, 'Common'),
  ('Potion', 'consumable', 'Wine of the Blood', '30 gp', 3000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 5, 'Rare'),
  ('Potion', 'consumable', 'Bloodhammer Reserve (Select)', '35 gp', 3500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 6, 'Uncommon'),
  ('Potion', 'consumable', 'Eidetic Potion', '40 gp', 4000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 6, 'Common'),
  ('Potion', 'consumable', 'Healing Potion (Moderate)', '50 gp', 5000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 6, 'Common'),
  ('Potion', 'consumable', 'Lesser Crimson Godsblood Serum', '50 gp', 5000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 6, 'Rare'),
  ('Potion', 'consumable', 'Octopus Potion (Lesser)', '50 gp', 5000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 6, 'Common'),
  ('Potion', 'consumable', 'Philter of Empty Dreams', '90 gp', 9000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 6, 'Rare'),
  ('Potion', 'consumable', 'Potion of Retaliation (Moderate)', '50 gp', 5000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 6, 'Common'),
  ('Potion', 'consumable', 'Potion of Swimming', '50 gp', 5000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 6, 'Common'),
  ('Potion', 'consumable', 'Tentacle Potion (Lesser)', '33 gp', 3300, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 6, 'Common'),
  ('Potion', 'consumable', 'Truth Potion', '46 gp', 4600, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 6, 'Uncommon'),
  ('Potion', 'consumable', 'Empath''s Cordial', '65 gp', 6500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 7, 'Common'),
  ('Potion', 'consumable', 'Energy Breath Potion (Lesser)', '70 gp', 7000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 7, 'Common'),
  ('Potion', 'consumable', 'Fey Dragonet Liqueur (Lesser)', '70 gp', 7000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 7, 'Uncommon'),
  ('Potion', 'consumable', 'Hovering Potion', '55 gp', 5500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 7, 'Common'),
  ('Potion', 'consumable', 'Ration Tonic (Greater)', '55 gp', 5500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 7, 'Common'),
  ('Potion', 'consumable', 'Serum of Sex Shift', '60 gp', 6000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 7, 'Common'),
  ('Potion', 'consumable', 'Bloodhammer Reserve (Black Label)', '100 gp', 10000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 8, 'Uncommon'),
  ('Potion', 'consumable', 'Potion of Disguise (Moderate)', '100 gp', 10000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 8, 'Uncommon'),
  ('Potion', 'consumable', 'Potion of Flying', '100 gp', 10000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 8, 'Common'),
  ('Potion', 'consumable', 'Potion of Quickness', '90 gp', 9000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 8, 'Common'),
  ('Potion', 'consumable', 'Potion of Shared Life', '95 gp', 9500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 8, 'Common'),
  ('Potion', 'consumable', 'Quenching Potion', '85 gp', 8500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 8, 'Common'),
  ('Potion', 'consumable', 'Roaring Potion (Lesser)', '90 gp', 9000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 8, 'Common'),
  ('Potion', 'consumable', 'Shrinking Potion (Greater)', '90 gp', 9000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 8, 'Common'),
  ('Potion', 'consumable', 'Octopus Potion (Moderate)', '130 gp', 13000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 9, 'Common'),
  ('Potion', 'consumable', 'Potion of Minute Echoes', '125 gp', 12500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 9, 'Common'),
  ('Potion', 'consumable', 'Effervescent Decoction', '160 gp', 16000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 10, 'Uncommon'),
  ('Potion', 'consumable', 'Immovable Potion', '160 gp', 16000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 10, 'Common'),
  ('Potion', 'consumable', 'Mutagenic Renovator', '180 gp', 18000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 10, 'Uncommon'),
  ('Potion', 'consumable', 'Potion of Annulment (Lesser)', '200 gp', 20000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 10, 'Rare'),
  ('Potion', 'consumable', 'Potion of Grounding', '185 gp', 18500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 10, 'Common'),
  ('Potion', 'consumable', 'Potion of Resistance (Moderate)', '180 gp', 18000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 10, 'Common'),
  ('Potion', 'consumable', 'Potion of Stable Form', '180 gp', 18000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 10, 'Common'),
  ('Potion', 'consumable', 'Sairazul Blue', '180 gp', 18000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 10, 'Rare'),
  ('Potion', 'consumable', 'Tentacle Potion (Moderate)', '155 gp', 15500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 10, 'Common'),
  ('Potion', 'consumable', 'Vengeful Demon''s Tears', '160 gp', 16000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 10, 'Uncommon'),
  ('Potion', 'consumable', 'Enigma-Sight Potion', '250 gp', 25000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 11, 'Common'),
  ('Potion', 'consumable', 'Potion of Disguise (Greater)', '300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 11, 'Uncommon'),
  ('Potion', 'consumable', 'Potion of Swimming (Greater)', '250 gp', 25000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 11, 'Common'),
  ('Potion', 'consumable', 'Dragonfly Potion', '310 gp', 31000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 12, 'Uncommon'),
  ('Potion', 'consumable', 'Elysian Dew', '375 gp', 37500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 12, 'Uncommon'),
  ('Potion', 'consumable', 'Energy Breath Potion (Moderate)', '400 gp', 40000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 12, 'Common'),
  ('Potion', 'consumable', 'Fey Dragonet Liqueur', '400 gp', 40000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 12, 'Uncommon'),
  ('Potion', 'consumable', 'Greater Soldier''s Syrup', '400 gp', 40000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 12, 'Uncommon'),
  ('Potion', 'consumable', 'Moderate Crimson Godsblood Serum', '400 gp', 40000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 12, 'Rare'),
  ('Potion', 'consumable', 'Phoenix Flask', '350 gp', 35000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 12, 'Common'),
  ('Potion', 'consumable', 'Potion of Retaliation (Greater)', '400 gp', 40000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 12, 'Common'),
  ('Potion', 'consumable', 'Potion of Truespeech', '320 gp', 32000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 12, 'Uncommon'),
  ('Potion', 'consumable', 'Cayden''s Brew (Double)', '480 gp', 48000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 13, 'Common'),
  ('Potion', 'consumable', 'Octopus Potion (Greater)', '500 gp', 50000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 13, 'Common'),
  ('Potion', 'consumable', 'Panacea', '450 gp', 45000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 13, 'Uncommon'),
  ('Potion', 'consumable', 'Roaring Potion (Moderate)', '550 gp', 55000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 13, 'Common'),
  ('Potion', 'consumable', 'Rovagug''s Mud', '600 gp', 60000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 13, 'Common'),
  ('Potion', 'consumable', 'Time Shield Potion', '600 gp', 60000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 13, 'Common'),
  ('Potion', 'consumable', 'Potion of Resistance (Greater)', '850 gp', 85000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 14, 'Common'),
  ('Potion', 'consumable', 'Tentacle Potion (Greater)', '660 gp', 66000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 14, 'Common'),
  ('Potion', 'consumable', 'Potion of Annulment (Moderate)', '1,300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 15, 'Rare'),
  ('Potion', 'consumable', 'Potion of Flying (Greater)', '1,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 15, 'Common'),
  ('Potion', 'consumable', 'Potion of Stable Form (Greater)', '1,800 gp', 80000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 16, 'Common'),
  ('Potion', 'consumable', 'Truesight Potion', '1,500 gp', 50000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 16, 'Common'),
  ('Potion', 'consumable', 'Energy Breath Potion (Greater)', '3,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 17, 'Common'),
  ('Potion', 'consumable', 'Fey Dragonet Liqueur (Greater)', '3,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 17, 'Uncommon'),
  ('Potion', 'consumable', 'Cayden''s Brew (Triple)', '3,200 gp', 20000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 18, 'Common'),
  ('Potion', 'consumable', 'Greater Crimson Godsblood Serum', '5,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 18, 'Rare'),
  ('Potion', 'consumable', 'Healing Potion (Major)', '5,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 18, 'Common'),
  ('Potion', 'consumable', 'Major Soldier''s Syrup', '5,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 18, 'Uncommon'),
  ('Potion', 'consumable', 'Potion of Retaliation (Major)', '5,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 18, 'Common'),
  ('Potion', 'consumable', 'Potion of Undetectability', '4,400 gp', 40000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 18, 'Common'),
  ('Potion', 'consumable', 'Roaring Potion (Greater)', '3,600 gp', 60000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 18, 'Common'),
  ('Potion', 'consumable', 'Rovagug''s Mud (Greater)', '4,800 gp', 80000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 18, 'Common'),
  ('Potion', 'consumable', 'Potion of Annulment (Greater)', '13,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 20, 'Rare'),
  ('Potion', 'consumable', 'Starsong Nectar', '14,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=18', 'Potion', 20, 'Rare'),
  ('Huile', 'consumable', 'Digly''s Oil of Sympathy (Minor)', '40 gp', 4000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 1, 'Rare'),
  ('Huile', 'consumable', 'Merciful Balm', '3 gp', 300, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 1, 'Common'),
  ('Huile', 'consumable', 'Nectar of Purification', '3 gp', 300, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 1, 'Common'),
  ('Huile', 'consumable', 'Oil of Unlife (Minor)', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 1, 'Common'),
  ('Huile', 'consumable', 'Shielding Salve', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 1, 'Common'),
  ('Huile', 'consumable', 'Anticorrosion Oil', '6 gp', 600, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 2, 'Common'),
  ('Huile', 'consumable', 'Oil of Potency', '7 gp', 700, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 2, 'Common'),
  ('Huile', 'consumable', 'Oil of Skating', '5 gp', 500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 2, 'Common'),
  ('Huile', 'consumable', 'Oil of Weightlessness', '6 gp', 600, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 2, 'Common'),
  ('Huile', 'consumable', 'Bane Oil', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 3, 'Uncommon'),
  ('Huile', 'consumable', 'Burial Oil', '10 gp', 1000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 3, 'Uncommon'),
  ('Huile', 'consumable', 'Digly''s Oil of Sympathy (Lesser)', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 3, 'Rare'),
  ('Huile', 'consumable', 'Life-Boosting Oil (Lesser)', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 3, 'Uncommon'),
  ('Huile', 'consumable', 'Oil of Mending', '9 gp', 900, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 3, 'Common'),
  ('Huile', 'consumable', 'Oil of Unlife (Lesser)', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 3, 'Common'),
  ('Huile', 'consumable', 'Serpent Oil (Lesser)', '8 gp', 800, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 3, 'Common'),
  ('Huile', 'consumable', 'Anointing Oil', '18 gp', 1800, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 4, 'Uncommon'),
  ('Huile', 'consumable', 'Ghost Oil', '18 gp', 1800, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 4, 'Common'),
  ('Huile', 'consumable', 'Restful Salve', '30 gp', 3000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 5, 'Uncommon'),
  ('Huile', 'consumable', 'Serpent Oil (Moderate)', '24 gp', 2400, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 5, 'Common'),
  ('Huile', 'consumable', 'Statue Skin Salve', '25 gp', 2500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 5, 'Uncommon'),
  ('Huile', 'consumable', 'Tricky Liniment', '25 gp', 2500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 5, 'Common'),
  ('Huile', 'consumable', 'Wounding Oil', '45 gp', 4500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 5, 'Uncommon'),
  ('Huile', 'consumable', 'Cindergrass Poultice', '33 gp', 3300, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 6, 'Uncommon'),
  ('Huile', 'consumable', 'Digly''s Oil of Sympathy (Moderate)', '50 gp', 5000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 6, 'Rare'),
  ('Huile', 'consumable', 'Oil of Swiftness', '50 gp', 5000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 6, 'Uncommon'),
  ('Huile', 'consumable', 'Oil of Unlife (Moderate)', '50 gp', 5000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 6, 'Common'),
  ('Huile', 'consumable', 'Oil of Weightlessness (Greater)', '36 gp', 3600, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 6, 'Common'),
  ('Huile', 'consumable', 'Salve of Antiparalysis', '40 gp', 4000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 6, 'Common'),
  ('Huile', 'consumable', 'Life-Boosting Oil (Moderate)', '70 gp', 7000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 7, 'Uncommon'),
  ('Huile', 'consumable', 'Saints'' Balm', '70 gp', 7000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 7, 'Uncommon'),
  ('Huile', 'consumable', 'Serpent Oil (Greater)', '56 gp', 5600, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 7, 'Common'),
  ('Huile', 'consumable', 'Topology Protoplasm', '70 gp', 7000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 7, 'Common'),
  ('Huile', 'consumable', 'Weapon-Weird Oil', '55 gp', 5500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 7, 'Common'),
  ('Huile', 'consumable', 'Oil of Dynamism', '85 gp', 8500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 8, 'Uncommon'),
  ('Huile', 'consumable', 'Ghostly Portal Paint', '120 gp', 12000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 9, 'Uncommon'),
  ('Huile', 'consumable', 'Oil of Corpse Restoration', '150 gp', 15000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 9, 'Uncommon'),
  ('Huile', 'consumable', 'Anointing Oil (Greater)', '180 gp', 18000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 10, 'Uncommon'),
  ('Huile', 'consumable', 'Panaceatic Salve', '155 gp', 15500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 10, 'Uncommon'),
  ('Huile', 'consumable', 'Burial Oil (Greater)', '250 gp', 25000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 11, 'Uncommon'),
  ('Huile', 'consumable', 'Fundamental Oil', '220 gp', 22000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 11, 'Uncommon'),
  ('Huile', 'consumable', 'Life-Boosting Oil (Greater)', '300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 11, 'Uncommon'),
  ('Huile', 'consumable', 'Oil of Keen Edges', '250 gp', 25000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 11, 'Uncommon'),
  ('Huile', 'consumable', 'Oil of Ownership (Greater)', '210 gp', 21000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 11, 'Common'),
  ('Huile', 'consumable', 'Serpent Oil (Major)', '225 gp', 22500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 11, 'Common'),
  ('Huile', 'consumable', 'Digly''s Oil of Sympathy (Greater)', '400 gp', 40000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 12, 'Rare'),
  ('Huile', 'consumable', 'Oil of Animation', '330 gp', 33000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 12, 'Uncommon'),
  ('Huile', 'consumable', 'Oil of Potency (Greater)', '400 gp', 40000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 12, 'Common'),
  ('Huile', 'consumable', 'Salve of Antiparalysis (Greater)', '325 gp', 32500, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 12, 'Common'),
  ('Huile', 'consumable', 'Life-Boosting Oil (Major)', '1,300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 15, 'Uncommon'),
  ('Huile', 'consumable', 'Obfuscation Oil', '1,200 gp', 20000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 15, 'Common'),
  ('Huile', 'consumable', 'Serpent Oil (True)', '1,100 gp', 10000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 15, 'Common'),
  ('Huile', 'consumable', 'Oil of Dynamism (Greater)', '1,400 gp', 40000, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 16, 'Uncommon'),
  ('Huile', 'consumable', 'Digly''s Oil of Sympathy (Major)', '5,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 18, 'Rare'),
  ('Huile', 'consumable', 'Oil of Unlife (Major)', '5,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 18, 'Common'),
  ('Huile', 'consumable', 'Oil of Potency (Major)', '8,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 19, 'Common'),
  ('Huile', 'consumable', 'Antimagic Oil', '13,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=15&Subcategory=17', 'Huile', 20, 'Rare'),
  ('Élixir', 'consumable', 'Addiction Suppressant (Lesser)', '2 gp', 200, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Rare'),
  ('Élixir', 'consumable', 'Affliction Suppressant (Lesser)', '3 gp', 300, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Antidote (Lesser)', '3 gp', 300, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Antiplague (Lesser)', '3 gp', 300, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Bendy-Arm Mutagen (Lesser)', '3 gp', 300, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Bestial Mutagen (Lesser)', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Cheetah''s Elixir (Lesser)', '3 gp', 300, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Cognitive Mutagen (Lesser)', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Deadweight Mutagen (Lesser)', '3 gp', 300, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Drakeheart Mutagen (Lesser)', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Eagle-Eye Elixir (Lesser)', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Elixir of Gender Transformation (Lesser)', '1 gp', 100, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Elixir of Life (Minor)', '3 gp', 300, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Elsie''s Excellent Bottled Vim', '3 gp', 300, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Rare'),
  ('Élixir', 'consumable', 'Energy Mutagen (Lesser)', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Juggernaut Mutagen (Lesser)', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Leaper''s Elixir (Lesser)', '3 gp', 300, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Numbing Tonic (Minor)', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Quicksilver Mutagen (Lesser)', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Sanguine Mutagen (Lesser)', '3 gp', 300, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Serene Mutagen (Lesser)', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Silvertongue Mutagen (Lesser)', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Skeptic''s Elixir (Lesser)', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Uncommon'),
  ('Élixir', 'consumable', 'Theatrical Mutagen (Lesser)', '3 gp', 300, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'Vaccine (Minor)', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Common'),
  ('Élixir', 'consumable', 'War Blood Mutagen (Lesser)', '4 gp', 400, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 1, 'Uncommon'),
  ('Élixir', 'consumable', 'Bottled Catharsis (Minor)', '5 gp', 500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 2, 'Common'),
  ('Élixir', 'consumable', 'Boulderhead Bock', '5 gp', 500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 2, 'Uncommon'),
  ('Élixir', 'consumable', 'Bravo''s Brew (Lesser)', '7 gp', 700, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 2, 'Common'),
  ('Élixir', 'consumable', 'Cat''s Eye Elixir', '7 gp', 700, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 2, 'Common'),
  ('Élixir', 'consumable', 'Comprehension Elixir (Lesser)', '7 gp', 700, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 2, 'Common'),
  ('Élixir', 'consumable', 'Darkvision Elixir (Lesser)', '6 gp', 600, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 2, 'Common'),
  ('Élixir', 'consumable', 'Soothing Tonic (Lesser)', '7 gp', 700, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 2, 'Common'),
  ('Élixir', 'consumable', 'Spiced Demonade', '8 gp', 800, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 2, 'Rare'),
  ('Élixir', 'consumable', 'Surging Serum (Minor)', '5 gp', 500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 2, 'Common'),
  ('Élixir', 'consumable', 'Winterstep Elixir (Minor)', '6 gp', 600, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 2, 'Uncommon'),
  ('Élixir', 'consumable', 'Bendy-Arm Mutagen (Moderate)', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 3, 'Common'),
  ('Élixir', 'consumable', 'Blood Booster (Lesser)', '9 gp', 900, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 3, 'Common'),
  ('Élixir', 'consumable', 'Blood Sight Elixir (Lesser)', '100 gp', 10000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 3, 'Uncommon'),
  ('Élixir', 'consumable', 'Cognitive Mutagen (Moderate)', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 3, 'Common'),
  ('Élixir', 'consumable', 'Deadweight Mutagen (Moderate)', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 3, 'Common'),
  ('Élixir', 'consumable', 'Drakeheart Mutagen (Moderate)', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 3, 'Common'),
  ('Élixir', 'consumable', 'Elixir of Gender Transformation (Moderate)', '8 gp', 800, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 3, 'Common'),
  ('Élixir', 'consumable', 'Energy Mutagen (Moderate)', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 3, 'Common'),
  ('Élixir', 'consumable', 'Juggernaut Mutagen (Moderate)', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 3, 'Common'),
  ('Élixir', 'consumable', 'Olfactory Obfuscator', '9 gp', 900, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 3, 'Common'),
  ('Élixir', 'consumable', 'Prey Mutagen (Moderate)', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 3, 'Rare'),
  ('Élixir', 'consumable', 'Quicksilver Mutagen (Moderate)', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 3, 'Common'),
  ('Élixir', 'consumable', 'Sanguine Mutagen (Moderate)', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 3, 'Common'),
  ('Élixir', 'consumable', 'Serene Mutagen (Moderate)', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 3, 'Common'),
  ('Élixir', 'consumable', 'Silvertongue Mutagen (Moderate)', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 3, 'Common'),
  ('Élixir', 'consumable', 'Theatrical Mutagen (Moderate)', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 3, 'Common'),
  ('Élixir', 'consumable', 'Vaccine (Lesser)', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 3, 'Common'),
  ('Élixir', 'consumable', 'War Blood Mutagen (Moderate)', '12 gp', 1200, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 3, 'Uncommon'),
  ('Élixir', 'consumable', 'Applereed Mutagen (Lesser)', '20 gp', 2000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 4, 'Rare'),
  ('Élixir', 'consumable', 'Bomber''s Eye Elixir (Lesser)', '14 gp', 1400, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 4, 'Common'),
  ('Élixir', 'consumable', 'Bottled Catharsis (Lesser)', '15 gp', 1500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 4, 'Common'),
  ('Élixir', 'consumable', 'Capsaicin Tonic', '17 gp', 1700, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 4, 'Uncommon'),
  ('Élixir', 'consumable', 'Cooling Elixir (Lesser)', '15 gp', 1500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 4, 'Common'),
  ('Élixir', 'consumable', 'Darkvision Elixir (Moderate)', '11 gp', 1100, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 4, 'Common'),
  ('Élixir', 'consumable', 'Lesser Elixir of the Peaks', '1 gp, 5 sp', 150, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 4, 'Rare'),
  ('Élixir', 'consumable', 'Mistform Elixir (Lesser)', '18 gp', 1800, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 4, 'Common'),
  ('Élixir', 'consumable', 'Stone Fist Elixir', '13 gp', 1300, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 4, 'Common'),
  ('Élixir', 'consumable', 'Witchwarg Elixir (Lesser)', '15 gp', 1500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 4, 'Common'),
  ('Élixir', 'consumable', 'Cheetah''s Elixir (Moderate)', '25 gp', 2500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 5, 'Common'),
  ('Élixir', 'consumable', 'Contagion Metabolizer (Lesser)', '30 gp', 3000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 5, 'Common'),
  ('Élixir', 'consumable', 'Elixir of Life (Lesser)', '30 gp', 3000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 5, 'Common'),
  ('Élixir', 'consumable', 'Ichthyosis Mutagen', '24 gp', 2400, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 5, 'Rare'),
  ('Élixir', 'consumable', 'Numbing Tonic (Lesser)', '30 gp', 3000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 5, 'Common'),
  ('Élixir', 'consumable', 'Sea Touch Elixir (Lesser)', '22 gp', 2200, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 5, 'Common'),
  ('Élixir', 'consumable', 'Sixfingers Elixir (Lesser)', '25 gp', 2500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 5, 'Uncommon'),
  ('Élixir', 'consumable', 'Soothing Tonic (Moderate)', '28 gp', 2800, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 5, 'Common'),
  ('Élixir', 'consumable', 'Stone Body Mutagen (Lesser)', '22 gp', 2200, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 5, 'Common'),
  ('Élixir', 'consumable', 'Viperous Elixir (Lesser)', '25 gp', 2500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 5, 'Common'),
  ('Élixir', 'consumable', 'Addiction Suppressant (Moderate)', '30 gp', 3000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 6, 'Rare'),
  ('Élixir', 'consumable', 'Affliction Suppressant (Moderate)', '35 gp', 3500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 6, 'Common'),
  ('Élixir', 'consumable', 'Antidote (Moderate)', '35 gp', 3500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 6, 'Common'),
  ('Élixir', 'consumable', 'Antiplague (Moderate)', '35 gp', 3500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 6, 'Common'),
  ('Élixir', 'consumable', 'Blood Sight Elixir (Moderate)', '400 gp', 40000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 6, 'Uncommon'),
  ('Élixir', 'consumable', 'Elixir of Gender Transformation (Greater)', '35 gp', 3500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 6, 'Common'),
  ('Élixir', 'consumable', 'Frogskin Tincture', '50 gp', 5000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 6, 'Common'),
  ('Élixir', 'consumable', 'Mistform Elixir (Moderate)', '56 gp', 5600, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 6, 'Common'),
  ('Élixir', 'consumable', 'Skeptic''s Elixir (Moderate)', '50 gp', 5000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 6, 'Uncommon'),
  ('Élixir', 'consumable', 'Vaccine (Moderate)', '50 gp', 5000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 6, 'Common'),
  ('Élixir', 'consumable', 'Winterstep Elixir (Lesser)', '36 gp', 3600, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 6, 'Uncommon'),
  ('Élixir', 'consumable', 'Comprehension Elixir (Greater)', '54 gp', 5400, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 7, 'Common'),
  ('Élixir', 'consumable', 'Leaper''s Elixir (Greater)', '55 gp', 5500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 7, 'Common'),
  ('Élixir', 'consumable', 'Moderate Elixir of the Peaks', '6 gp', 600, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 7, 'Rare'),
  ('Élixir', 'consumable', 'Ommatophoric Mutagen', '65 gp', 6500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 7, 'Uncommon'),
  ('Élixir', 'consumable', 'Bottled Catharsis (Moderate)', '75 gp', 7500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 8, 'Common'),
  ('Élixir', 'consumable', 'Darkvision Elixir (Greater)', '90 gp', 9000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 8, 'Common'),
  ('Élixir', 'consumable', 'Mnemonic Acid', '75 gp', 7500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 8, 'Uncommon'),
  ('Élixir', 'consumable', 'Psychic Colors Elixir', '100 gp', 10000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 8, 'Uncommon'),
  ('Élixir', 'consumable', 'Surging Serum (Moderate)', '75 gp', 7500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 8, 'Common'),
  ('Élixir', 'consumable', 'Viperous Elixir (Moderate)', '85 gp', 8500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 8, 'Common'),
  ('Élixir', 'consumable', 'Blood Sight Elixir (Greater)', '115 gp', 11500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 9, 'Uncommon'),
  ('Élixir', 'consumable', 'Cheetah''s Elixir (Greater)', '110 gp', 11000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 9, 'Common'),
  ('Élixir', 'consumable', 'Chromatic Jellyfish Oil (Lesser)', '120 gp', 12000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 9, 'Common'),
  ('Élixir', 'consumable', 'Elixir of Life (Moderate)', '150 gp', 15000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 9, 'Common'),
  ('Élixir', 'consumable', 'Mana-Rattler Liniment', '110 gp', 11000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 9, 'Uncommon'),
  ('Élixir', 'consumable', 'Pallesthetic Mutagen', '150 gp', 15000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 9, 'Uncommon'),
  ('Élixir', 'consumable', 'Spiderfoot Brew (Moderate)', '150 gp', 15000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 9, 'Common'),
  ('Élixir', 'consumable', 'Addiction Suppressant (Greater)', '140 gp', 14000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 10, 'Rare'),
  ('Élixir', 'consumable', 'Affliction Suppressant (Greater)', '160 gp', 16000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 10, 'Common'),
  ('Élixir', 'consumable', 'Antidote (Greater)', '160 gp', 16000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 10, 'Common'),
  ('Élixir', 'consumable', 'Antiplague (Greater)', '160 gp', 16000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 10, 'Common'),
  ('Élixir', 'consumable', 'Baleblood Draft', '155 gp', 15500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 10, 'Rare'),
  ('Élixir', 'consumable', 'Bravo''s Brew (Moderate)', '150 gp', 15000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 10, 'Common'),
  ('Élixir', 'consumable', 'Eagle-Eye Elixir (Greater)', '200 gp', 20000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 10, 'Common'),
  ('Élixir', 'consumable', 'Mistform Elixir (Greater)', '180 gp', 18000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 10, 'Common'),
  ('Élixir', 'consumable', 'Olfactory Obfuscator (Greater)', '225 gp', 22500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 10, 'Common'),
  ('Élixir', 'consumable', 'Winterstep Elixir (Moderate)', '160 gp', 16000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 10, 'Uncommon'),
  ('Élixir', 'consumable', 'Bendy-Arm Mutagen (Greater)', '300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 11, 'Common'),
  ('Élixir', 'consumable', 'Bestial Mutagen (Greater)', '300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 11, 'Common'),
  ('Élixir', 'consumable', 'Blood Booster (Moderate)', '225 gp', 22500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 11, 'Common'),
  ('Élixir', 'consumable', 'Cognitive Mutagen (Greater)', '300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 11, 'Common'),
  ('Élixir', 'consumable', 'Contagion Metabolizer (Moderate)', '300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 11, 'Common'),
  ('Élixir', 'consumable', 'Drakeheart Mutagen (Greater)', '300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 11, 'Common'),
  ('Élixir', 'consumable', 'Energy Mutagen (Greater)', '300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 11, 'Common'),
  ('Élixir', 'consumable', 'Greater Elixir of the Peaks', '25 gp', 2500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 11, 'Rare'),
  ('Élixir', 'consumable', 'Juggernaut Mutagen (Greater)', '300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 11, 'Common'),
  ('Élixir', 'consumable', 'Prey Mutagen (Greater)', '300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 11, 'Rare'),
  ('Élixir', 'consumable', 'Quicksilver Mutagen (Greater)', '300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 11, 'Common'),
  ('Élixir', 'consumable', 'Sanguine Mutagen (Greater)', '300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 11, 'Common'),
  ('Élixir', 'consumable', 'Serene Mutagen (Greater)', '300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 11, 'Common'),
  ('Élixir', 'consumable', 'Silvertongue Mutagen (Greater)', '300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 11, 'Common'),
  ('Élixir', 'consumable', 'Sixfingers Elixir (Moderate)', '250 gp', 25000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 11, 'Uncommon'),
  ('Élixir', 'consumable', 'Skeptic''s Elixir (Greater)', '300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 11, 'Uncommon'),
  ('Élixir', 'consumable', 'Theatrical Mutagen (Greater)', '300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 11, 'Common'),
  ('Élixir', 'consumable', 'Viperous Elixir (Greater)', '225 gp', 22500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 11, 'Common'),
  ('Élixir', 'consumable', 'Applereed Mutagen (Moderate)', '400 gp', 40000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 12, 'Rare'),
  ('Élixir', 'consumable', 'Blood Sight Elixir (Major)', '350 gp', 35000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 12, 'Uncommon'),
  ('Élixir', 'consumable', 'Bottled Catharsis (Greater)', '325 gp', 32500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 12, 'Common'),
  ('Élixir', 'consumable', 'Cooling Elixir (Moderate)', '320 gp', 32000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 12, 'Common'),
  ('Élixir', 'consumable', 'Sea Touch Elixir (Moderate)', '300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 12, 'Common'),
  ('Élixir', 'consumable', 'Stone Body Mutagen (Moderate)', '300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 12, 'Common'),
  ('Élixir', 'consumable', 'Surging Serum (Greater)', '325 gp', 32500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 12, 'Common'),
  ('Élixir', 'consumable', 'Vaccine (Greater)', '400 gp', 40000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 12, 'Common'),
  ('Élixir', 'consumable', 'Witchwarg Elixir (Moderate)', '320 gp', 32000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 12, 'Common'),
  ('Élixir', 'consumable', 'Elixir of Life (Greater)', '600 gp', 60000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 13, 'Common'),
  ('Élixir', 'consumable', 'Numbing Tonic (Greater)', '600 gp', 60000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 13, 'Common'),
  ('Élixir', 'consumable', 'Addiction Suppressant (Major)', '500 gp', 50000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 14, 'Rare'),
  ('Élixir', 'consumable', 'Affliction Suppressant (Major)', '675 gp', 67500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 14, 'Common'),
  ('Élixir', 'consumable', 'Antidote (Major)', '675 gp', 67500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 14, 'Common'),
  ('Élixir', 'consumable', 'Antiplague (Major)', '675 gp', 67500, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 14, 'Common'),
  ('Élixir', 'consumable', 'Bomber''s Eye Elixir (Greater)', '700 gp', 70000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 14, 'Common'),
  ('Élixir', 'consumable', 'Chromatic Jellyfish Oil (Moderate)', '800 gp', 80000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 14, 'Common'),
  ('Élixir', 'consumable', 'Malleable Mixture (Greater)', '750 gp', 75000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 14, 'Uncommon'),
  ('Élixir', 'consumable', 'Winterstep Elixir (Greater)', '640 gp', 64000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 14, 'Uncommon'),
  ('Élixir', 'consumable', 'Elixir of Life (Major)', '1,300 gp', 30000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 15, 'Common'),
  ('Élixir', 'consumable', 'Major Elixir of the Peaks', '120 gp', 12000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 15, 'Rare'),
  ('Élixir', 'consumable', 'Sea Touch Elixir (Greater)', '920 gp', 92000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 15, 'Common'),
  ('Élixir', 'consumable', 'Stone Body Mutagen (Greater)', '920 gp', 92000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 15, 'Common'),
  ('Élixir', 'consumable', 'Apricot of Bestial Might', '2,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 16, 'Uncommon'),
  ('Élixir', 'consumable', 'Cooling Elixir (Greater)', '1,400 gp', 40000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 16, 'Common'),
  ('Élixir', 'consumable', 'Eagle-Eye Elixir (Major)', '2,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 16, 'Common'),
  ('Élixir', 'consumable', 'Numbing Tonic (Major)', '1,400 gp', 40000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 16, 'Common'),
  ('Élixir', 'consumable', 'Witchwarg Elixir (Greater)', '1,400 gp', 40000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 16, 'Common'),
  ('Élixir', 'consumable', 'Bendy-Arm Mutagen (Major)', '3,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 17, 'Common'),
  ('Élixir', 'consumable', 'Bestial Mutagen (Major)', '3,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 17, 'Common'),
  ('Élixir', 'consumable', 'Cognitive Mutagen (Major)', '3,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 17, 'Common'),
  ('Élixir', 'consumable', 'Deadweight Mutagen (Major)', '3,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 17, 'Common'),
  ('Élixir', 'consumable', 'Drakeheart Mutagen (Major)', '3,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 17, 'Common'),
  ('Élixir', 'consumable', 'Energy Mutagen (Major)', '3,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 17, 'Common'),
  ('Élixir', 'consumable', 'Juggernaut Mutagen (Major)', '3,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 17, 'Common'),
  ('Élixir', 'consumable', 'Prey Mutagen (Major)', '3,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 17, 'Rare'),
  ('Élixir', 'consumable', 'Quicksilver Mutagen (Major)', '3,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 17, 'Common'),
  ('Élixir', 'consumable', 'Serene Mutagen (Major)', '3,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 17, 'Common'),
  ('Élixir', 'consumable', 'Silvertongue Mutagen (Major)', '3,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 17, 'Common'),
  ('Élixir', 'consumable', 'Sixfingers Elixir (Greater)', '2,500 gp', 50000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 17, 'Uncommon'),
  ('Élixir', 'consumable', 'Soothing Tonic (Major)', '2,700 gp', 70000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 17, 'Common'),
  ('Élixir', 'consumable', 'Spiderfoot Brew (Greater)', '2,500 gp', 50000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 17, 'Common'),
  ('Élixir', 'consumable', 'Theatrical Mutagen (Major)', '3,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 17, 'Common'),
  ('Élixir', 'consumable', 'War Blood Mutagen (Major)', '3,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 17, 'Uncommon'),
  ('Élixir', 'consumable', 'Applereed Mutagen (Greater)', '5,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 18, 'Rare'),
  ('Élixir', 'consumable', 'Blood Booster (Greater)', '3,400 gp', 40000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 18, 'Common'),
  ('Élixir', 'consumable', 'Bottled Catharsis (Major)', '3,250 gp', 25000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 18, 'Common'),
  ('Élixir', 'consumable', 'Surging Serum (Major)', '3,250 gp', 25000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 18, 'Common'),
  ('Élixir', 'consumable', 'Vaccine (Major)', '5,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 18, 'Common'),
  ('Élixir', 'consumable', 'Chromatic Jellyfish Oil (Greater)', '5,200 gp', 20000, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 19, 'Common'),
  ('Élixir', 'consumable', 'Contagion Metabolizer (Greater)', '8,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 19, 'Common'),
  ('Élixir', 'consumable', 'Elixir of Life (True)', '8,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 19, 'Common'),
  ('Élixir', 'consumable', 'Numbing Tonic (True)', '8,000 gp', 0, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 19, 'Common'),
  ('Élixir', 'consumable', 'Elixir of Rejuvenation', null, null, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 20, 'Uncommon'),
  ('Élixir', 'consumable', 'Sun Orchid Elixir', null, null, 'https://2e.aonprd.com/Equipment.aspx?Category=6&Subcategory=8', 'Élixir', 20, 'Rare')
on conflict (aon_url, name_en) do update set
  source_tab = excluded.source_tab,
  equipment_kind = excluded.equipment_kind,
  price_label = excluded.price_label,
  price_cp = excluded.price_cp,
  item_type = excluded.item_type,
  level = excluded.level,
  rarity = excluded.rarity;

commit;

